apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: host-pvc
spec:
  volumeName: hostpv
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi